config/routes.rb
Rails.application.routes.draw do
	    root :to => 'apprenticeships#index'
  resources :apprenticeships
  resources :padawans
  resources :jedis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apprenticeship.rb
class Apprenticeship < ActiveRecord::Base
      # attr_accessible :jedi_id, :padawan_id
      belongs_to :jedi
      belongs_to :padawan
    end

app/models/jedi.rb
class Jedi < ActiveRecord::Base
      # attr_accessible :name
      has_many :apprenticeships
      has_many :padawans, :through => :apprenticeships
    end

app/models/padawan.rb
class Padawan < ActiveRecord::Base
  # attr_accessible :name
  has_many :apprenticeships
  has_many :jedis, :through => :apprenticeships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apprenticeships_controller.rb
class ApprenticeshipsController < ApplicationController
  before_action :set_apprenticeship, only: [:show, :edit, :update, :destroy]

  # GET /apprenticeships
  # GET /apprenticeships.json
  def index
    @apprenticeships = Apprenticeship.all
  end

  # GET /apprenticeships/1
  # GET /apprenticeships/1.json
  def show
  end

  # GET /apprenticeships/new
  def new
    @apprenticeship = Apprenticeship.new
  end

  # GET /apprenticeships/1/edit
  def edit
  end

  # POST /apprenticeships
  # POST /apprenticeships.json
  def create
    @apprenticeship = Apprenticeship.new(apprenticeship_params)


      if @apprenticeship.save
        redirect_to @apprenticeship and return
        render :show, status: :created, location: @apprenticeship 
      else
        render :new
        render json: @apprenticeship.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /apprenticeships/1
  # PATCH/PUT /apprenticeships/1.json
  def update
    respond_to do |format|
      if @apprenticeship.update(apprenticeship_params)
        format.html { redirect_to @apprenticeship, notice: 'Apprenticeship was successfully updated.' }
        format.json { render :show, status: :ok, location: @apprenticeship }
      else
        format.html { render :edit }
        format.json { render json: @apprenticeship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apprenticeships/1
  # DELETE /apprenticeships/1.json
  def destroy
    @apprenticeship.destroy
    respond_to do |format|
      format.html { redirect_to apprenticeships_url, notice: 'Apprenticeship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apprenticeship
      @apprenticeship = Apprenticeship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apprenticeship_params
      params.require(:apprenticeship).permit(:jedi_id, :padawan_id)
    end
end

app/controllers/jedis_controller.rb
class JedisController < ApplicationController
  before_action :set_jedi, only: [:show, :edit, :update, :destroy]

  # GET /jedis
  # GET /jedis.json
  def index
    @jedis = Jedi.all
  end

  # GET /jedis/1
  # GET /jedis/1.json
  def show
  end

  # GET /jedis/new
  def new
    @jedi = Jedi.new
  end

  # GET /jedis/1/edit
  def edit
  end

  # POST /jedis
  # POST /jedis.json
  def create
    @jedi = Jedi.new(jedi_params)

    respond_to do |format|
      if @jedi.save
        format.html { redirect_to @jedi, notice: 'Jedi was successfully created.' }
        format.json { render :show, status: :created, location: @jedi }
      else
        format.html { render :new }
        format.json { render json: @jedi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jedis/1
  # PATCH/PUT /jedis/1.json
  def update
    respond_to do |format|
      if @jedi.update(jedi_params)
        format.html { redirect_to @jedi, notice: 'Jedi was successfully updated.' }
        format.json { render :show, status: :ok, location: @jedi }
      else
        format.html { render :edit }
        format.json { render json: @jedi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jedis/1
  # DELETE /jedis/1.json
  def destroy
    @jedi.destroy
    respond_to do |format|
      format.html { redirect_to jedis_url, notice: 'Jedi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jedi
      @jedi = Jedi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jedi_params
      params.require(:jedi).permit(:name)
    end
end

app/controllers/padawans_controller.rb
class PadawansController < ApplicationController
  before_action :set_padawan, only: [:show, :edit, :update, :destroy]

  # GET /padawans
  # GET /padawans.json
  def index
    @padawans = Padawan.all
  end

  # GET /padawans/1
  # GET /padawans/1.json
  def show
  end

  # GET /padawans/new
  def new
    @padawan = Padawan.new
  end

  # GET /padawans/1/edit
  def edit
  end

  # POST /padawans
  # POST /padawans.json
  def create
    @padawan = Padawan.new(padawan_params)

    respond_to do |format|
      if @padawan.save
        format.html { redirect_to @padawan, notice: 'Padawan was successfully created.' }
        format.json { render :show, status: :created, location: @padawan }
      else
        format.html { render :new }
        format.json { render json: @padawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /padawans/1
  # PATCH/PUT /padawans/1.json
  def update
    respond_to do |format|
      if @padawan.update(padawan_params)
        format.html { redirect_to @padawan, notice: 'Padawan was successfully updated.' }
        format.json { render :show, status: :ok, location: @padawan }
      else
        format.html { render :edit }
        format.json { render json: @padawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /padawans/1
  # DELETE /padawans/1.json
  def destroy
    @padawan.destroy
    respond_to do |format|
      format.html { redirect_to padawans_url, notice: 'Padawan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_padawan
      @padawan = Padawan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def padawan_params
      params.require(:padawan).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apprenticeships_helper.rb
module ApprenticeshipsHelper
end

app/helpers/jedis_helper.rb
module JedisHelper
end

app/helpers/padawans_helper.rb
module PadawansHelper
end

app/views/apprenticeships/_form.html.erb
<%= form_for(apprenticeship) do |f| %>
  <% if apprenticeship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apprenticeship.errors.count, "error") %> prohibited this apprenticeship from being saved:</h2>

      <ul>
      <% apprenticeship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
        <%= f.select :jedi_id, Jedi.all.collect { |p| [ p.name, p.id ] } %>
      </div>
      <div class="field">
        <%= f.select :padawan_id, Padawan.all.collect { |p| [ p.name, p.id ] } %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/apprenticeships/edit.html.erb
<h1>Editing Apprenticeship</h1>

<%= render 'form', apprenticeship: @apprenticeship %>

<%= link_to 'Show', @apprenticeship %> |
<%= link_to 'Back', apprenticeships_path %>

app/views/apprenticeships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apprenticeships</h1>

<table>
  <thead>
    <tr>
      <th>Jedi</th>
      <th>Padawan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apprenticeships.each do |apprenticeship| %>
      <tr>
        <td><%= apprenticeship.jedi.name %></td>
        <td><%= apprenticeship.padawan.name %></td>
        <td><%= link_to 'Show', apprenticeship %></td>
        <td><%= link_to 'Edit', edit_apprenticeship_path(apprenticeship) %></td>
        <td><%= link_to 'Destroy', apprenticeship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apprenticeship', new_apprenticeship_path %>

 <%= link_to 'New Jedi', new_jedi_path %>
    <%= link_to 'New Padawan', new_padawan_path %>

app/views/apprenticeships/new.html.erb
<h1>New Apprenticeship</h1>

<%= render 'form', apprenticeship: @apprenticeship %>

<%= link_to 'Back', apprenticeships_path %>

app/views/apprenticeships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Jedi:</b>
  <%= @apprenticeship.jedi.name %>
</p>

<p>
  <b>Padawan:</b>
  <%= @apprenticeship.padawan.name %>
</p>

<%= link_to 'Edit', edit_apprenticeship_path(@apprenticeship) %> |
<%= link_to 'Back', apprenticeships_path %>

app/views/jedis/_form.html.erb
<%= form_for(jedi) do |f| %>
  <% if jedi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jedi.errors.count, "error") %> prohibited this jedi from being saved:</h2>

      <ul>
      <% jedi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jedis/edit.html.erb
<h1>Editing Jedi</h1>

<%= render 'form', jedi: @jedi %>

<%= link_to 'Show', @jedi %> |
<%= link_to 'Back', jedis_path %>

app/views/jedis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jedis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jedis.each do |jedi| %>
      <tr>
        <td><%= jedi.name %></td>
        <td><%= link_to 'Show', jedi %></td>
        <td><%= link_to 'Edit', edit_jedi_path(jedi) %></td>
        <td><%= link_to 'Destroy', jedi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jedi', new_jedi_path %>

app/views/jedis/new.html.erb
<h1>New Jedi</h1>

<%= render 'form', jedi: @jedi %>

<%= link_to 'Back', jedis_path %>

app/views/jedis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jedi.name %>
</p>

<%= link_to 'Edit', edit_jedi_path(@jedi) %> |
<%= link_to 'Back', jedis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sithfighters</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/padawans/_form.html.erb
<%= form_for(padawan) do |f| %>
  <% if padawan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(padawan.errors.count, "error") %> prohibited this padawan from being saved:</h2>

      <ul>
      <% padawan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/padawans/edit.html.erb
<h1>Editing Padawan</h1>

<%= render 'form', padawan: @padawan %>

<%= link_to 'Show', @padawan %> |
<%= link_to 'Back', padawans_path %>

app/views/padawans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Padawans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @padawans.each do |padawan| %>
      <tr>
        <td><%= padawan.name %></td>
        <td><%= link_to 'Show', padawan %></td>
        <td><%= link_to 'Edit', edit_padawan_path(padawan) %></td>
        <td><%= link_to 'Destroy', padawan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Padawan', new_padawan_path %>

app/views/padawans/new.html.erb
<h1>New Padawan</h1>

<%= render 'form', padawan: @padawan %>

<%= link_to 'Back', padawans_path %>

app/views/padawans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @padawan.name %>
</p>

<%= link_to 'Edit', edit_padawan_path(@padawan) %> |
<%= link_to 'Back', padawans_path %>